name: Alpine Linux Setup

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting main branch

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub runners use Ubuntu, but we'll install Alpine via Docker

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # This checks out your code so it can be used in the next steps

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2  # This sets up Docker buildx for advanced builds
    
    - name: Run Alpine Linux Docker Container
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace alpine:latest /bin/sh -c "
          echo 'Running Alpine Linux in GitHub Actions...';
          apk add --no-cache curl git;  # Example: Install curl and git in Alpine
          curl --version;  # Verify curl is installed
        "
